---
# tasks/main.yml
- name: Install Apache web server
  package:
    name: "{{ webserver_package }}"
    state: present

- name: Copy default site configuration
  template:
    src: default.j2
    dest: /etc/httpd/conf.d/000-default.conf
    mode: 0644
    remote_src: yes
- name: Create HTML files
  template:
    src: "/home/kajal_lufha/Assignment2/roles/webserver/templates/defaults.j2"
    remote_src: yes
    dest: "{{ webserver_document_root }}/{{ item.filename }}"
    mode: 0444
  with_items: "{{ webserver_files }}"

- name: Start Apache web server
  service:
    name: "{{ webserver_service }}"
    state: started
    enabled: yes
    daemon_reload: yes
  notify:
    - restart Apache

- name: Ensure Apache web server autostarts at system reboots
  service:
    name: "{{ webserver_service }}"
    enabled: yes

- name: Set SELinux permissions for Apache web server
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_os_family == 'RedHat'

